#!/bin/bash

# title of menu items
ins="Install package(s) from official repo"
upg="Upgrade system"
rmr="Remove recently installed package(s)"
rmro="Remove recently installed official package(s)"
rmra="Remove recently installed AUR package(s)"
rms="Remove installed package(s)"
rmso="Remove installed official package(s)"
rmsa="Remove installed AUR package(s)"
pdif="Resolve pacnew and pacsave files (pacdiff)"
clr="Clear uninstalled packages from cache (paccache)"
rmud="Remove unneeded dependencies (orphans)"
nws="Show news from Archlinux homepage"
sh="Start shell"

# fzf commands for listing "to be installed" and "to be removed" packages respectively
fzfi() {
    fzf --layout=reverse --multi --preview='pacman --color always -Si {1}' --preview-window=right:60%:wrap
}

fzfr() {
    fzf --layout=reverse --multi --preview='pacman --color always -Qi {1}' --preview-window=right:60%:wrap
}

# grep extended regexp of packages to ignore when listing installed packages to remove
pacstoign="^(base|efibootmgr|grub|linux|linux-firmware|linux-lts|man-db|man-pages)$"

# list of package groups to ignore while listing installed packages to remove
grpstoign=(base-devel)

# menu items to show
menu="$ins\n$upg\n$rmr\n$rmro\n$rmra\n$rms\n$rmso\n$rmsa\n$pdif\n$clr\n$rmud\n$nws\n$sh"


filter () {
    grep -Fxvf <(pacman -Qqg "${grpstoign[@]}") | grep -Ev "$pacstoign"
}

keyprompt() {
    read -s -n1 -p $'\n Press any key to continue or ^C to exit...'
}

while true ; do
    clear
    case $(echo -e "$menu" | fzf --layout=reverse) in
        "$ins")
            mapfile -t pacstoins < <(pacman -Slq | fzfi)
            if (( ${#pacstoins[@]} )) ; then
                clear
                trap : INT
                yay -S "${pacstoins[@]}"
                trap - INT
                keyprompt
            fi
            ;;
        "$upg")
            trap : INT
            yay -Syu
            trap - INT
            keyprompt
            ;;
        "$rmr")
            mapfile -t pacstorem < <(
                tac /var/log/pacman.log | grep -aF "[ALPM] installed" |
                 awk '!x[$4] {x[$4]=1; print $4}' |
                  grep -Fxf <(pacman -Qqe | filter) |
                   fzfr)
            if (( ${#pacstorem[@]} )) ; then
                clear
                trap : INT
                yay -Rns "${pacstorem[@]}"
                trap - INT
                keyprompt
            fi
            ;;
        "$rmro")
            mapfile -t pacstorem < <(
                tac /var/log/pacman.log | grep -aF "[ALPM] installed" |
                 awk '!x[$4] {x[$4]=1; print $4}' |
                  grep -Fxf <(pacman -Qqen | filter) |
                   fzfr)
            if (( ${#pacstorem[@]} )) ; then
                clear
                trap : INT
                yay -Rns "${pacstorem[@]}"
                trap - INT
                keyprompt
            fi
            ;;
        "$rmra")
            mapfile -t pacstorem < <(
                tac /var/log/pacman.log | grep -aF "[ALPM] installed" |
                 awk '!x[$4] {x[$4]=1; print $4}' |
                  grep -Fxf <(pacman -Qqem) |
                   fzfr)
            if (( ${#pacstorem[@]} )) ; then
                clear
                trap : INT
                yay -Rns "${pacstorem[@]}"
                trap - INT
                keyprompt
            fi
            ;;
        "$rms")
            mapfile -t pacstorem < <(pacman -Qqe | filter | fzfr)
            if (( ${#pacstorem[@]} )) ; then
                clear
                trap : INT
                yay -Rns "${pacstorem[@]}"
                trap - INT
                keyprompt
            fi
            ;;
        "$rmso")
            mapfile -t pacstorem < <(pacman -Qqen | filter | fzfr)
            if (( ${#pacstorem[@]} )) ; then
                clear
                trap : INT
                yay -Rns "${pacstorem[@]}"
                trap - INT
                keyprompt
            fi
            ;;
        "$rmsa")
            mapfile -t pacstorem < <(pacman -Qqem | fzfr)
            if (( ${#pacstorem[@]} )) ; then
                clear
                trap : INT
                yay -Rns "${pacstorem[@]}"
                trap - INT
                keyprompt
            fi
            ;;
        "$pdif")
            trap : INT
            sudo pacdiff
            trap - INT
            keyprompt
            ;;
        "$clr")
            trap : INT
            paccache -ruk0
            trap - INT
            keyprompt
            ;;
        "$rmud")
            mapfile -t orpstorem < <(pacman -Qdtq)
            if (( ${#orpstorem[@]} )) ; then
                trap : INT
                yay -Rns "${orpstorem[@]}"
                trap - INT
            else
                echo -e "\e[1;32m==> \e[1;37mNo unneeded dependencies (orphans) found for removing\e[0m"
            fi
            keyprompt
            ;;
        "$nws")
            yay -Pw | less -R
            ;;
        "$sh")
            "$SHELL"
            ;;
        *)
            break
            ;;
    esac
done
clear
